apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: addons
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/MuratDz/argocd.git
        revision: HEAD
        directories:
          - path: addons/*
  template:
    metadata:
      name: '{{path}}'
    spec:
      project: addons
      source:
        repoURL: https://github.com/MuratDz/argocd.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path}}'
