apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: addons
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: git@github.com:elsabahnur/argocd.git
        revision: HEAD
        directories:
          - path: argocd/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: addons
      source:
        repoURL: git@github.com:elsabahnur/argocd.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
#      syncPolicy:
#        automated: {}
#        syncOptions:
#          - CreateNamespace=true
#          - ServerSideApply=true  ## Not working on k8s 1.18, apply after upgrade >1.21
