apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

helmCharts:
- name: kube-prometheus-stack
  releaseName: kube-prometheus-stack
  version: 17.0.2
  repo: 'https://prometheus-community.github.io/helm-charts'
  valuesFile: values.yaml

patches:
- target:
      version: v1
      kind: Endpoints
      name: kube-prometheus-stack-kube-etcd
  path: patches/replace-ns.yaml
- target:
      version: v1
      kind: Service
      name: kube-prometheus-stack-kube-scheduler
  path: patches/replace-ns.yaml
- target:
      version: v1
      kind: Service
      name: kube-prometheus-stack-coredns
  path: patches/replace-ns.yaml
- target:
      version: v1
      kind: Service
      name: kube-prometheus-stack-kube-controller-manager
  path: patches/replace-ns.yaml
- target:
      version: v1
      kind: Service
      name: kube-prometheus-stack-kube-proxy
  path: patches/replace-ns.yaml
- target:
      version: v1
      kind: Service
      name: kube-prometheus-stack-kube-etcd
  path: patches/replace-ns.yaml
